spring:
  application:
    name: basic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data/schema.sql
#      schema-locations: classpath:data/data.sql
