spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:springbatchdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---

spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:13306/springbatch?useUnicode=true&character=Encoding=utf8
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always
